name: Python package

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  #

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Memperbarui pip
        pip install -r requirements.txt  # Instal dependensi dari file requirements.txt

    - name: Run tests
      run: |
        pytest  # Gantilah dengan perintah lain sesuai dengan cara Anda menguji kode
